# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b2ca36505b02150a652c296c4a6bff7420fb06ea50f42eae2798e362c1666a2ab3e67c65ab4a0742a4a7fdc32e417a6c48d107b53a98a35c9eb970705e47942

test:
  secret_key_base: 460110bc395b326e7a0d1d7d10568e74831b846a214268b4c582c9afd262d4c54b2212b87813e6e0ff83192264f95f8390d246754b0aa03e5f6aacd8fd04aabe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
